---
name: test
on: [pull_request, push]

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # latest stable version of Python
          python-version: "3.x"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install
        run: |
          pip install -U pip
          pip install -e .
          pip list

      - name: Run tests
        run: pytest -v
